#!/bin/sh

topdir="${0%/*}"
base=

usage()
{
	echo "usage: $0 [options]"
	echo ""
	echo "options:"
	echo "  -h, --help    display this help screen and exit"
}

while test $# -gt 0; do
	case $1 in
		-h | --help)
			usage $0
			exit 0
			;;

		*)
			usage $0
			exit 1
			;;
	esac
done

while read branch; do
	if test -z "$base"; then
		base=$branch

		if ! git checkout for-next; then
			git checkout -b for-next $base
		else
			git reset --hard $base
		fi

		continue
	fi

	git merge --no-ff $branch
done < "$topdir/branches"
