#!/bin/sh

basedir="${0%/*}"
configdir="${basedir}/configs"
outputdir="build/$(git describe)/drm"

function usage()
{
	echo "usage: $0 [options] [config...]"
	echo ""
	echo "options:"
	echo "  -h, --help        display help screen and exit"
	echo "  -o, --output DIR  set output directory"
	echo "  -v, --verbose     increase verbosity"
}

while test $# -ne 0; do
	if test -n "$prev"; then
		eval "$prev=$1"
		shift; prev=
		continue
	fi

	case $1 in
		-h | --help)
			usage $0
			exit 0
			;;

		-o | --output)
			prev=outputdir
			shift
			;;

		-v | --verbose)
			verbose=yes
			shift
			;;

		-*)
			usage $0
			exit 1
			;;

		*)
			configs="$configs $1"
			shift
			;;
	esac
done

if test -z "$configs"; then
	for config in "${configdir}"/*; do
		configs="$configs ${config##${configdir}/}"
	done
fi

find drivers/gpu/drm -name '*.c' | while read source; do
	base="${source%.c}"
	object="${base}.o"

	found=no

	for config in $configs; do
		KBUILD_OUTPUT="${outputdir}/${config}"

		if test -f "$KBUILD_OUTPUT/$object"; then
			found=yes
			break
		fi
	done

	if test "x$found" = "xno"; then
		echo "$source is not compiled"
	fi
done

#for config in $configs; do
#	KBUILD_OUTPUT="${outputdir}/${config}"
#
#	find drivers/gpu/drm -name '*.c' | while read source; do
#		base="${source%.c}"
#		object="${base}.o"
#
#		if ! test -f "$KBUILD_OUTPUT/$object"; then
#			echo "$config: $source is not compiled"
#		fi
#	done
#done
